Update configure script and ppmpss.sh script
The configure script now adds the configuration to the ppmpss.sh script.
It will check if the system has an ed available and if it's suitable.

A new --help case is added to configure for documentation purposes.

The ppmpss.sh script will now check to make sure a command has been
passed - though none have been implemented, yet.

Fixed extra space in copyright notice.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -5,7 +5,7 @@
 # SPDX-License-Identifier: GPL-3.0-or-later
 #
 # Portable package manager made in POSIX shell script
-# Copyright (C) 2023  astral
+# Copyright (C) 2023 astral
 # 
 # This file is part of ppmpss.
 # 
@@ -33,17 +33,69 @@ do
 		fi
 		exit 0
 		;;
+	--help)
+		cat <<- eof
+		Configure the build and install system for ppmpss.
+
+		This script will generate a Makefile config and write your
+		settings into ppmpss.
+
+		usage:
+		$0 [--reset] [--help] [--prefix=<PREFIX>]
+
+		--reset
+		    Reset files the way before running configure. The PREFIX
+		    written to ppmpss.sh needs to be reset manually as the
+		    reset option shouldn't depend on ed
+		--help
+		    Display this screen
+		--prefix=<PREFIX>
+		    Configure the build system and ppmpss to use the specified
+		    PREFIX for installation.
+		eof
+		exit 0
+		;;
 	--prefix=*)
 		PREFIX=${arg##*=}
 		;;
 	*)
-		printf >&2 "usage: %s [--reset] [--prefix=<PREFIX>]\n" "$0"
+		printf >&2 "usage: %s [--reset] [--help] [--prefix=<PREFIX>]\n" "$0"
 		exit 1
 		;;
 	esac
 done
 
+# See if system has ed command
+printf "%-58s" "Checking for ed command..."
+if [ -z "$(command -v ed)" ]
+then
+	echo
+	printf >&2 "ed command not found\n"
+	exit 1
+fi
+printf "OK\n"
+
+# See if ed can edit ppmpss.sh
+printf "%-58s" "Checking if available ed is suitable..."
+if ! ed -s ppmpss.sh < /dev/null > /dev/null 2>&1
+then
+	echo
+	printf >&2 "ed command not suitable\n"
+	exit 1
+fi
+printf "OK\n"
+
 : "${PREFIX:=/usr/local}"
+
+# Let ppmpss know about configured PREFIX
+printf "%-58s" "Writing PREFIX to ppmpss..."
+if ! printf '%s\n' '29d' '29i' "PREFIX=$PREFIX" '.' 'w' | ed -s ppmpss.sh
+then
+	echo
+	printf >&2 "Failed to write PREFIX to ppmpss\n"
+	exit 1
+fi
+printf "OK\n"
 
 cat << eof > config.mk
 DESTDIR =
@@ -54,5 +106,7 @@ if [ -f Makefile.in ]
 then
 	mv Makefile.in Makefile
 fi
+
+printf "PREFIX: %s\n" "$PREFIX"
 
 exit 0
